# Generated by Django 4.2 on 2023-05-04 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gsmApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('view_count', models.IntegerField(blank=True, default=0)),
                ('slug', models.SlugField(blank=True, default='')),
                ('Brand', models.ManyToManyField(blank=True, to='gsmApp.brand')),
                ('Model', models.ManyToManyField(blank=True, to='gsmApp.model')),
            ],
            options={
                'ordering': ('sno',),
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('modelpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gsmApp.model')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.blogcomment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
