# Generated by Django 4.2 on 2023-05-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsmApp', '0003_user_profile_credits'),
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='categorypost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gsmApp.category'),
        ),
    ]
