# Generated by Django 4.2 on 2023-05-08 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsmApp', '0003_user_profile_credits'),
        ('blogApp', '0002_blogcomment_categorypost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Brand',
        ),
        migrations.AddField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='article',
            name='Model',
        ),
        migrations.AddField(
            model_name='article',
            name='Model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gsmApp.model'),
        ),
    ]
