# Generated by Django 4.2 on 2023-05-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_article_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='active',
            new_name='verified',
        ),
    ]
