# Generated by Django 4.2 on 2023-08-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adsense_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsense_code', models.TextField(blank=True, null=True)),
                ('place_at', models.CharField(choices=[('topBar', 'topBar'), ('sideBar', 'sideBar')], max_length=20)),
                ('adsense_image', models.ImageField(blank=True, upload_to='adsense')),
                ('adsense_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='shortner_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='adsense')),
                ('time', models.IntegerField(default=0, help_text='The time value should be set in seconds')),
            ],
        ),
    ]
