# Generated by Django 4.2 on 2023-08-26 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_download_limit',
            name='download_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
