# Generated by Django 4.2 on 2023-08-27 03:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0002_alter_daily_download_limit_download_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_download_limit',
            name='download_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
