# Generated by Django 4.2 on 2023-08-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0003_alter_daily_download_limit_download_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='free_files_permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_download_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='daily_download_limit',
            field=models.IntegerField(default=0),
        ),
    ]
