# Generated by Django 4.2 on 2023-08-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptionApp', '0004_free_files_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_download_limit',
            old_name='download_count',
            new_name='free_file_downloads',
        ),
        migrations.AddField(
            model_name='daily_download_limit',
            name='subscription_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
