# Generated by Django 4.2 on 2023-08-25 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adschoice', models.CharField(choices=[('localads', 'local ads'), ('adsenseads', 'adsense ads'), ('affliateads', 'affliate ads')], max_length=15)),
                ('banner_image', models.ImageField(blank=True, upload_to='ads')),
                ('url', models.URLField()),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Timestemp', models.CharField(help_text='in days', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='custom_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('header', 'header'), ('footer', 'footer')], default='', max_length=15)),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='model',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('Model_code', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('Chipset', models.CharField(default='', max_length=200)),
                ('chipset_description', models.CharField(max_length=400, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('Brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gsmApp.brand')),
                ('Cat', models.ManyToManyField(blank=True, to='gsmApp.category')),
                ('Tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('time_stemp', models.IntegerField(default=0, help_text='enter in days')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='onsitedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Website_Title', models.CharField(blank=True, max_length=100)),
                ('Website_URL', models.URLField(blank=True)),
                ('Website_Logo', models.ImageField(blank=True, upload_to='logo')),
                ('Meta_Description', models.CharField(blank=True, max_length=300)),
                ('Meta_Keywords', models.CharField(blank=True, max_length=500)),
                ('Contact_email', models.EmailField(blank=True, max_length=50)),
                ('Mail_Password', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_page', models.CharField(choices=[('about', 'About'), ('contact', 'Contact'), ('refund-policy', 'Refund Policy'), ('return-policy', 'Return Policy'), ('privacy-policy', 'Privacy Policy'), ('cancellation-policy', 'Cancellation Policy'), ('terms-of-services', 'Terms Of Services')], default='', max_length=50)),
                ('title', models.CharField(default='', max_length=500)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='socialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook_URL', models.URLField(blank=True)),
                ('Instragram_URL', models.URLField(blank=True)),
                ('Twitter_URL', models.URLField(blank=True)),
                ('Youtube_URL', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNomber', models.CharField(blank=True, max_length=14)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('referral_code', models.CharField(blank=True, default='', max_length=10)),
                ('referrer_code', models.CharField(blank=True, default='', max_length=10)),
                ('credits', models.IntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('size', models.CharField(default='', max_length=20)),
                ('desc', models.TextField(default='')),
                ('file', models.FileField(blank=True, default='', upload_to='')),
                ('url', models.URLField(blank=True)),
                ('varient', models.CharField(default='', max_length=100)),
                ('update_at', models.DateField(auto_now=True)),
                ('pro', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('Brand', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gsmApp.brand')),
                ('Categories', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gsmApp.category')),
                ('Model', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gsmApp.model')),
                ('Tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
