# Generated by Django 4.2 on 2023-05-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='referrer_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
