# Generated by Django 4.2 on 2023-05-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsmApp', '0002_user_profile_referrer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
